# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - ISEOS-FA-Py12

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # REMOVED: Virtual environment and package installation
      # Let Azure Functions handle this with remote build

      - name: Validate requirements.txt
        run: |
          echo "Validating requirements.txt..."
          cat requirements.txt
          python -c "
          with open('requirements.txt', 'r') as f:
              lines = [line.strip() for line in f if line.strip() and not line.startswith('#')]
              print(f'Found {len(lines)} package requirements')
              for line in lines:
                  print(f'  - {line}')
          "

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "venv/*" ".git/*" ".github/*" "__pycache__/*" "*.pyc" ".python_packages/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55132670CE604AD18AE1272024510536 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA16AF689DE4403D8636C4829DE151C0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2C0CCD15FA694FCD9060386E32A549CB }}

      - name: List files before deployment (debug)
        run: |
          echo "Files in deployment directory:"
          ls -la
          echo "Python files:"
          find . -name "*.py" -type f
          echo "Requirements content:"
          cat requirements.txt

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'iseos-fa-py12'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_xxx }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
