# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - ISEOS-FA-Py12

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.12' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          # Install dependencies to .python_packages for Azure Functions
          pip install -r requirements.txt --target ./.python_packages/lib/site-packages
          # Also install in venv for any build-time needs
          pip install -r requirements.txt

      # Optional: Add step to run tests here

      - name: List files before zipping (debug)
        run: |
          echo "Files in root directory:"
          ls -la
          echo "Files in .python_packages:"
          ls -la .python_packages/lib/site-packages/ || echo "No .python_packages directory"
          echo "Checking for azure-cosmos:"
          find .python_packages/ -name "*cosmos*" -type d || echo "No cosmos packages found"

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "venv/*" ".git/*" ".github/*" "__pycache__/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55132670CE604AD18AE1272024510536 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA16AF689DE4403D8636C4829DE151C0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2C0CCD15FA694FCD9060386E32A549CB }}

      - name: List files before deployment (debug)
        run: |
          echo "Files in deployment directory:"
          ls -la
          echo "Python files:"
          find . -name "*.py" -type f

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'ISEOS-FA-Py12'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: false
          enable-oryx-build: false
          