# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - ISEOS-FA-Py12

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Copy installed packages to .python_packages for Azure Functions
          mkdir -p .python_packages/lib/site-packages
          cp -r venv/lib/python*/site-packages/* .python_packages/lib/site-packages/

      - name: Validate installation
        run: |
          echo "Validating requirements.txt..."
          cat requirements.txt
          echo "Installed packages:"
          pip list
          echo "Contents of .python_packages:"
          ls -la .python_packages/lib/site-packages/
          echo "Key packages check:"
          ls -la .python_packages/lib/site-packages/ | grep -E "(requests|azure)"

      - name: Zip artifact for deployment
        run: |
          # FIXED: Include .python_packages but exclude venv and other unnecessary files
          zip -r release.zip . -x \
            "venv/*" \
            ".git/*" \
            ".github/*" \
            "__pycache__/*" \
            "*.pyc" \
            "*.pyo" \
            ".vscode/*" \
            ".pytest_cache/*" \
            "*.log"

      - name: Validate ZIP contents
        run: |
          echo "ZIP contents:"
          unzip -l release.zip | head -30
          echo "Checking if .python_packages is included:"
          unzip -l release.zip | grep -E "python_packages|azure|requests" || echo "No packages found in ZIP!"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55132670CE604AD18AE1272024510536 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA16AF689DE4403D8636C4829DE151C0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2C0CCD15FA694FCD9060386E32A549CB }}

      - name: List files before deployment (debug)
        run: |
          echo "Files in deployment directory:"
          ls -la
          echo "Python files:"
          find . -name "*.py" -type f
          echo "Requirements content:"
          cat requirements.txt
          echo ".python_packages contents:"
          ls -la .python_packages/lib/site-packages/ | head -20
          echo "Checking for requests package:"
          ls -la .python_packages/lib/site-packages/ | grep requests || echo "requests not found!"

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'iseos-fa-py12'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_xxx }}
          # REMOVED: These cause deployment failures on Consumption Plan (or set to false)
          scm-do-build-during-deployment: false
          enable-oryx-build: false
